ibm-build-lab/VAD-VAR-Workshop

- Sterling/docs/ConfigurationPart2.md
> Fix image filename

- Maximo/README.md
- Watson/102.md
- Watson/README.md
Fixes some small typos in the WA 102 lab as well in the README.
> Fixed some small typos

- Maximo/README.md
> update Maximo badge links

- Sterling/docs/ClientDemonstration.md
- Sterling/docs/ConfigurationPart2.md
Some small changes that should make the lab easier to understand.
> Sterling lab tweaks

- content/Watson/101.md
- gatsby-config.mjs
- src/components/replacements/BlockQuote.tsx
- src/components/replacements/ImageWrapper.tsx
- src/components/replacements/SmartLink.tsx
- src/components/replacements/TableWrapper.tsx
- src/components/replacements/index.ts
- src/pages/{mdx.fields__slug}.tsx
- src/styles/components/replacements/ImageWrapper.module.scss
- Removed frontmatter data from WA 101 lab to test hydration error
Code changes:
- Image optimization was causing slow build times. Opted to make optional and test performance for now.
- Add new `ImageWrapper` component
- Props for HTML replacements changed from custom interfaces to React defaults
> Optional image optimization

- .github/workflows/build-site.yml
- .github/workflows/deploy-static-site.yml
- .github/workflows/pull-request-testing.yml
- README.md
- content/Watson/101.md
- src/components/replacements/SubHeader.tsx
- Added back in frontmatter for WA 101 lab
Code changes:
- Fixed hydration error caused by `SubHeader` component
- Was caused by usage of the `Date` object causing a mismatch between date seconds which led to a hydration error
- Added a new workflow to run on PRs to main that will dry run the build of the site
- Added a new reusable workflow that builds the site
> Fix hydration error

- .github/workflows/build-site.yml
- .github/workflows/deploy-static-site.yml
- .github/workflows/pull-request-testing.yml
- N/A
Code changes:
- Edited reusable workflow to use artifact
> Testing reusable workflow

- content/README.md
- content/Sterling/README.md
- content/Sterling/docs/ClientDemonstration.md
- content/Sterling/docs/ConfigurationPart1.md
- content/Sterling/docs/ConfigurationPart2.md
- content/Sterling/docs/Overview.md
- content/Sterling/docs/index.md
- Updates top level page with new quiz block
- Switch to quiz blocks in Sterling DX lab
- Include Introduction in lab list on Sterling DX home page
> Update Sterling DX lab with new quizalert blocks

- content/test.md
- src/components/Layout.tsx
- src/components/TableOfContents.tsx
- src/components/replacements/CodeBlock.tsx
- src/styles/_variables.scss
- src/styles/components/Layout.module.scss
- src/styles/components/TableOfContents.module.scss
- src/styles/components/replacements/CodeBlock.module.scss
- src/styles/pages/{mdx.fields__slug}.module.scss
- Update test page
Code changes:
- Removed theming on the table of contents
- Content is now center at larger breakpoints
- Reverted to old sidebar for now
> Better responsiveness to breakpoints

- gatsby-config.mjs
- src/pages/{mdx.fields__slug}.tsx
- src/styles/components/Layout.module.scss
- src/styles/components/TableOfContents.module.scss
- src/styles/components/replacements/CodeBlock.module.scss
- src/styles/components/replacements/ImageWrapper.module.scss
- src/styles/globals.scss
- src/styles/pages/{mdx.fields__slug}.module.scss
- N/A
Code changes:
- Added margin so content stays in same position even without TOC
- Fixed scroll issue on page change
- Fixed inline code block not wrapping properly
- Images can now fill entirety of content width
> Small fixes

- content/Watson/102.md
- content/Watson/103.md
- Add quiz alerts to the watson assistant content
- Remove the section on IAM from the 102 lab
Code changes:
- N/A
> Add quiz alerts to the WA content

- content/Envizi/README.es.md
- content/Envizi/README.md
- Add  links to L3+ in sp + en Envizi readme
Code changes:
- N/a
> fix(Envizi links): add links for 3+ in readme

- content/Instana/102.es.md
- content/Instana/102.md
- Use quiz alert instead of green dot in Instana 102
Code changes:
> fix(Instana): make quiz alerts consistent

- Watson/README.md
- content/Instana/103.md
- Capitalized API in the Instana docs
Code changes:
- None
> Capitalize API.

- i18n.ts
- Add accent to Español.
Code changes:
- None
> Add accent to Español.

- content/Instana/101.es.md
- content/Instana/101.md
- content/Instana/103.es.md
- content/Instana/103.md
- Remove broken RobotShop link from deleted TZ env
- Update quiz alerts
> refactor: fix broken links and update some quiz alerts

- content/MLOps/100.es.md
- content/MLOps/100.md
- content/MLOps/101.es.md
- content/MLOps/101.md
- content/MLOps/104.es.md
- content/MLOps/104.md
- content/MLOps/105.es.md
- content/MLOps/105.md
- Update estimated lab times to reflect presentation
Code changes:
> Update lab times.

- content/EIS/101.es.md
- content/EIS/101.md
- content/EIS/README.es.md
- content/EIS/README.md
> Update EIS path.

- content/CP4I/100.md
- content/CP4I/101.md
- content/CP4I/102.md
- content/CP4I/103.md
- content/CP4I/README.md
> adding cp4i labs

- content/MLOps/105.es.md
- content/MLOps/105.md
- Remove resource values from MLOps 105
Code changes:
- N/A
> Removed resource values from MLOps 105

- content/Turbonomic/101.es.md
- content/Turbonomic/101.md
- content/Turbonomic/README.es.md
- content/Turbonomic/README.md
- Remove references to Madrid.
> Remove references to Madrid.

- content/MLOps/104.es.md
- content/MLOps/104.md
- updates note at end of 104 for turning off runtimes
> Customize note for 104

- content/Instana/103.es.md
- content/Instana/103.md
Fixes #127 
- update channel to **#instana-alerts**
> update channel for alerts

- content/Instana/103.es.md
- content/Instana/103.md
> Update Slack channel.

- content/Databand/README.md
- minor wording update to English lab readme to match current lab content
> Update Databand intro

- content/CP4I/101.es.md
DeepL translated a specific technical key value by mistake
> Revert translated literal.

- content/Envizi/101.es.md
- content/Envizi/102.es.md
- content/Envizi/103.es.md
- content/Envizi/104.es.md
- content/Envizi/105.es.md
- content/Envizi/105.md
- content/Envizi/106.es.md
- Translate new Envizi content
Code changes:
> feat(Envizi): translate new content

- content/WKC/101.es.md
- content/WKC/102.es.md
- content/WKC/103.es.md
- content/WKC/104.es.md
- content/WKC/106.es.md
- content/WKC/getting-started.es.md
- content/WKC/getting-started.md
Links on Spanish pages now link to other pages also in Spanish.
> WKC: Fix tables, Spanish links

- content/CP4I/103.es.md
- content/CP4I/104.es.md
- content/Envizi/103.es.md
- content/Turbonomic/103.es.md
- content/Turbonomic/105.es.md
- content/WKC/101.es.md
- content/WKC/102.es.md
- content/WKC/103.es.md
- content/WKC/104.es.md
- content/WKC/105.es.md
- content/WKC/106.es.md
- content/WKC/getting-started.es.md
- Fix frontmatter dates causing problem (A misformatted date causes gatsby to not be able to parse all dates correctly)
Code changes:
- N/A
> Fix date bug

- content/Envizi/105.es.md
- content/Envizi/105.md
- Add GH links for appconnect flows
Code changes:
> feat(Envizi): add appconnect GH links

- content/CP4I/README.es.md
- content/CP4I/README.md
- content/WKC/README.es.md
- content/WKC/README.md
- Update table of contents for WKC, CP4I
> Update table of contents for WKC, CP4I

- content/test.md
- src/components/replacements/BlockQuote/BlockQuote.module.scss
- src/components/replacements/BlockQuote/BlockQuote.tsx
- N/A
Code changes:
- Fixed multiline blockquotes
> Fix multiline blockquotes

- content/QRadar-SIEM/102.md
- Minor changes for better readability. Covers rest of document
- Adds quiz alert notes
> Edits for qradar siem lab2 pt2

- content/QRadar-SIEM/101.md
- content/QRadar-SIEM/104.md
- content/QRadar-SIEM/105.md
- content/QRadar-SIEM/106.md
- lab TODO notes removed from 101
- minor typos in 104 and 105
- image link fixes in 104, 105 and 106
> misc typos, update image links in 104-106

- content/Watson/101.es.md
- content/Watson/102.es.md
- content/Watson/103.es.md
- Add quiz alerts to spanish translations for WA
Code changes:
- N/A
> Add quiz alerts to spanish translations for WA

- content/QRadar-SIEM/102.md
- content/QRadar-SIEM/105.md
-  link and link formatting fixes 102
-  typo fix 102
-  md indentation fixes 105 in `#create-a-rule-for-the-bluecoat-events`
> QRadar SIEM lab typo and url fixes, md cleanup

- content/CP4I/100.md
- content/CP4I/101.md
- content/CP4I/102.md
> Update wording a bit.

- content/QRadar-SIEM/101.es.md
- content/QRadar-SIEM/101.md
- content/QRadar-SIEM/102.es.md
- content/QRadar-SIEM/102.md
- content/QRadar-SIEM/104.md
- content/QRadar-SIEM/105.md
- content/QRadar-SIEM/106.md
Some small fixes I made while working through the QRadar-SIEM labs. Fixes some broken links.
> Fix typos in QRadar-SIEM labs

- content/QRadar-SIEM/101.md
- content/QRadar-SIEM/103.es.md
- content/QRadar-SIEM/103.md
- content/QRadar-SIEM/104.es.md
- content/QRadar-SIEM/104.md
- content/QRadar-SIEM/105.es.md
- content/QRadar-SIEM/105.md
- content/QRadar-SIEM/106.es.md
- content/QRadar-SIEM/106.md
> Update to WireGuard.

- content/Maximo/VISUAL-INSPECTION-ACTION.md
Added overview of See, Learn, Do
> new updates to mvi action

- content/Watsonx/WatsonxAI/100.md
- content/Watsonx/WatsonxAI/101.md
- content/Watsonx/WatsonxAI/102.md
- content/Watsonx/WatsonxAI/103.md
- content/Watsonx/WatsonxAI/README.md
Add quiz question flags for watsonx.ai L3 labs
Minor formatting
> feat(watsonxai): add test question flags

- content/Watsonx/WatsonxAI/105.es.md
- content/Watsonx/WatsonxAI/105.md
http://localhost:8000/en/watsonx/watsonxai/105
http://localhost:8000/es/watsonx/watsonxai/105
> Lab 105: Langchain Spanish Translation

- content/Watsonx/CodeAssistant/README.es.md
- content/Watsonx/CodeAssistant/README.md
- content/Watsonx/README.es.md
- content/Watsonx/README.md
- gatsby-config.mjs
minor weaks to the watsonx code assistant wording
make public
> chore(watsonxCA): expose watsonx code assistant

- content/Watsonx/WatsonxAI/101.es.md
- content/Watsonx/WatsonxAI/101.md
- content/Watsonx/WatsonxAI/102.es.md
- content/Watsonx/WatsonxAI/102.md
- content/Watsonx/WatsonxAI/103.es.md
Fixes broken links to the prerequisites page.
> fix(watsonx.ai): fix prereqs links

- content/Watsonx/WatsonxAI/107.es.md
- content/Watsonx/WatsonxAI/README.es.md
- content/Watsonx/WatsonxAI/ref103.es.md
general doc updates
- add spanish translations for the following
- `Lab 107 -- RAG using Chroma DB`
-  `Reference 103`
- main watsonx.ai `README`
Code changes:
N/A
> add spanish translations for lab 107 and Reference Page 103

- content/Watsonx/WatsonxData/109.md
- content/Watsonx/WatsonxData/110.md
> removed prefix requirement in schema name

- content/Watsonx/WatsonxAI/100.es.md
- content/Watsonx/WatsonxAI/100.md
- content/Watsonx/WatsonxData/110.md
Remove the h3 markdown on techzone links
Minor update to data lab 110 wording
> fix(wxdata): minor update to lab 110

- content/Watsonx/WatsonxAI/103.md
- content/Watsonx/WatsonxAI/README.md
- content/Watsonx/WatsonxData/106.md
- content/Watsonx/WatsonxData/README.md
Fixes | Relates to https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/246
> Correct BP quiz pointers

- content/Watsonx/WatsonxAI/103.es.md
- content/Watsonx/WatsonxAI/108.es.md
- content/Watsonx/WatsonxAI/README.es.md
- content/Watsonx/WatsonxData/101.es.md
- content/Watsonx/WatsonxData/101.md
- content/Watsonx/WatsonxData/106.es.md
- content/Watsonx/WatsonxData/110.es.md
- content/Watsonx/WatsonxData/README.es.md
- content/Watsonx/WatsonxData/README.md
- content/Watsonx/WatsonxData/ref100.es.md
- content/Watsonx/WatsonxData/ref100.md
- content/Watsonx/WatsonxData/ref101.es.md
- content/Watsonx/WatsonxData/ref102.es.md
Fixes **[[issue link](https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/247)]**
- I also added Spanish translations for lab 108 under the watsonx.ai folder
Code changes:
> Miscellaneous translation updates

- content/Watsonx/WatsonxAI/105.md
Fixes N/a
- Update .ai 105 to add more descriptive JupyterHub instructions.
Code changes:
- .ai 105
> update JupyterHub instructions

- content/Watsonx/WatsonxData/Level-4/201.md
- content/Watsonx/WatsonxData/Level-4/204.md
- content/Watsonx/WatsonxData/Level-4/README.md
- Add quizalert for Spark lab
- Fix typos, links
> chore(cleanup): fix typos, links, quizalerts

- content/Watsonx/README.es.md
- content/Watsonx/README.md
- content/Watsonx/WatsonxGov/1.es.md
- content/Watsonx/WatsonxGov/102.es.md
- content/Watsonx/WatsonxGov/103.es.md
- content/Watsonx/WatsonxGov/104.es.md
- content/Watsonx/WatsonxGov/105.es.md
- content/Watsonx/WatsonxGov/106.es.md
- content/Watsonx/WatsonxGov/README.es.md
Fixes https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/344
- Translated and reviewed labs 102-106, 1, and readme
- Added watsonx governance link to the watsonx section
Code changes:
> watsonx.governance Spanish Translations

- content/Watsonx/Assistant/Level-4/203.es.md
- content/Watsonx/Assistant/Level-4/203.md
https://ibm.seismic.com/Link/Content/DCWpd8WCHQm2MGmFWQJBHmTHcg2d
- option 1 becomes option 2, typos, update links
Code changes:
> Content changes: LLM-powered search has been updated to use IBM Granite

- content/Watsonx/CodeAssistant/Ansible-Lightspeed/101.es.md
- content/Watsonx/CodeAssistant/Ansible-Lightspeed/102.es.md
- content/Watsonx/CodeAssistant/Ansible-Lightspeed/103.es.md
- content/Watsonx/CodeAssistant/Ansible-Lightspeed/104.es.md
- content/Watsonx/CodeAssistant/Ansible-Lightspeed/README.es.md
- content/Watsonx/CodeAssistant/README.es.md
- content/Watsonx/CodeAssistant/Z/111.es.md
- content/Watsonx/CodeAssistant/Z/112.es.md
- content/Watsonx/CodeAssistant/Z/113.es.md
- content/Watsonx/CodeAssistant/Z/114.es.md
- content/Watsonx/CodeAssistant/Z/README.es.md
Fixes https://github.com/ibm-build-lab/vest-content/issues/103
- Translated and reviewed the WCA for Z labs. Labs 101-104 and the readme file.
Code changes:
> WCA  for Z Spanish Translations

- content/Watsonx/WatsonxData/106.es.md
- content/Watsonx/WatsonxData/106.md
- content/Watsonx/WatsonxData/107.es.md
- content/Watsonx/WatsonxData/107.md
- content/Watsonx/WatsonxData/109.es.md
- content/Watsonx/WatsonxData/109.md
Fixes https://github.com/ibm-build-lab/VAD-VAR-Workshop/issues/371
- adjusted queries to use uppercase names for the db2catalog catalog
Code changes:
> watsonx.data L3 lab 106 query error

- content/Watsonx/WatsonxAI/files/203/LangChain_Integration.ipynb
> fix(langchain): update model_id_1 to 2

- content/Watsonx/WatsonxGov/102.es.md
- content/Watsonx/WatsonxGov/103.es.md
- content/Watsonx/WatsonxGov/104.es.md
- content/Watsonx/WatsonxGov/106.es.md
Fixes https://github.com/ibm-build-lab/vest-content/issues/121
Code changes:
> watsonx.gov L3: Update labs (Spanish Version)

- content/Watsonx/WatsonxGov/107.es.md
- content/Watsonx/WatsonxGov/README.es.md
- content/Watsonx/WatsonxGov/ref101.es.md
Fixes https://github.com/ibm-build-lab/vest-content/issues/124#event-12648895035
Code changes:
> watsonx.governance L3+ Spanish Translations

- content/Watsonx/WatsonxAI/102.es.md
- content/Watsonx/WatsonxAI/102.md
- content/Watsonx/WatsonxAI/105.es.md
Fixes https://github.com/ibm-build-lab/vest-content/issues/123
Code changes:
> watsonx.ai - Bogota workshop Feedback

- content/Turbonomic/101.es.md
- content/Turbonomic/102.es.md
- content/Turbonomic/103.es.md
- content/Turbonomic/104.es.md
- content/Turbonomic/105.es.md
- content/Turbonomic/106.es.md
- content/Turbonomic/README.es.md
Fixes https://github.com/ibm-build-lab/vest-content/issues/127
Code changes:
> Turbonomic L3 Content Spanish Translations

- content/Watsonx/WatsonxAI/files/205/rag_elasticsearch_free.ipynb
> 205 elasticsearch notebook make better description

- content/Watsonx/WatsonxAI/Level-4/206.md
> Ai lab 206: fix a typo

- content/Maximo/MASSuite/APP-SUITE-PREREQ.es.md
- content/Maximo/MASSuite/APP-SUITE-WORKSHOP.es.md
Fixing the links for real this time
> Fix image links in MAS L3 Spanish version, again

- content/labs/Watsonx/WatsonxAI/105.md
- content/labs/Watsonx/WatsonxAI/105/langchain-intro-cloud.ipynb
- content/labs/Watsonx/WatsonxAI/Level-4/201.md
- content/labs/Watsonx/WatsonxAI/Level-4/202.md
- content/labs/Watsonx/WatsonxAI/files/rag-with-chromadb.ipynb
Fixes N/a
- More fixes for asset file paths, notebook updates
Code changes:
> fix notebook file paths, fixes for langchain-intro book

- content/labs/Guardium/Level-4/202.md
- content/labs/Guardium/Level-4/203.md
> fix: fix broken image in lab 203 and address need for additional details in 202

- content/labs/Guardium/Level-4/204.md
ad-hoc fix to address broken images with GDP Lab 204
> fix: broken image in labe 204

- content/labs/Guardium/Level-4/205.md
- content/labs/Guardium/Level-4/207.md
ad-hoc fixes for GDP labs 205 and 207
> fix: address a few grammar issues, use new personas callouts, and fix image spacing

- src/app/[locale]/layout.tsx
> fix: add metadata to locale layout

- .github/workflows/deploy-static-site.yml
- site.config.ts
> fix: seo image and desc

- content/labs/Watsonx/WatsonxAI/Level-4/201.es.md
- content/labs/Watsonx/WatsonxAI/Level-4/201.md
- content/labs/Watsonx/WatsonxAI/Level-4/202.es.md
- content/labs/Watsonx/WatsonxAI/Level-4/202.md
> Updates links to new file structure
